[package]
name = "stamp-py"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Python bindings for STAMP structural alignment library"

[lib]
name = "stamp"
crate-type = ["cdylib"]

[dependencies]
stamp-core = { workspace = true }
pyo3 = { workspace = true }
numpy = { workspace = true }
ndarray = "0.16"

[lints]
workspace = true

[features]
default = []
extension-module = ["pyo3/extension-module"]
